server:
  port: 8089

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
    failFast: true
    retry:
      maxAttempts: 6
      initialInterval: 2000
      multiplier: 1.5
  profiles:
    active: dev
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
            - id: customer-service-route
              uri: lb://customer-service
              predicates:
                - Path=/api/customers/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}