global:
  message: Welcome to customer service dev environment!!

server:
  port: 8082

spring:
  datasource:
    url: ${CUSTOMER_SERVICE_MYSQL_URL:jdbc:mysql://localhost:3306/customers}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true