global:
  message: Welcome to order service prod environment!!

server:
  port: 8085

spring:
  datasource:
    url: ${ORDER_SERVICE_PROD_MYSQL_URL:jdbc:mysql://localhost:3306/orders_prod}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true