spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_SERVICE_MYSQL_URL:jdbc:mysql://localhost:3306/orders}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false